/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raden.janoko.kubera.ui;

import java.io.IOException;
import java.security.GeneralSecurityException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author ai
 */
public class Dash extends javax.swing.JFrame {
private raden.janoko.kubera.util.DBConfig d;
    /**
     * Creates new form Dash
     */
    public Dash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);
        jTabbedPane1.addTab("Home", jToolBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int x=JOptionPane.showConfirmDialog(rootPane, "apa anda ingin menghentikan aplikasi?", "HENTIKAN?", JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.NO_OPTION)new Dash().setVisible(true);
        this.setVisible(false);
        raden.janoko.kubera.util.Work.ending();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread(()->{
            try {
                d=raden.janoko.kubera.util.Work.loadDB();
                raden.janoko.kubera.util.Work.createReport();
                next();
                muatSemua();
                lanjut();
            } catch (ParserConfigurationException | SAXException | IOException | GeneralSecurityException | 
                    ClassNotFoundException | SQLException ex) {
                raden.janoko.kubera.util.Work.hindar(ex);
                raden.janoko.kubera.util.Work.ending();
            }setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }).start();this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    private void next() throws SQLException {
        while(!raden.janoko.kubera.util.Work.isKurangKas(d)){
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            raden.janoko.kubera.ui.oper.aset.AddKas a=new raden.janoko.kubera.ui.oper.aset.AddKas(this, true, d);
            a.setVisible(true);
            while(a.isVisible()){}
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }while(!raden.janoko.kubera.util.Work.isKurangPajak(d)){
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            raden.janoko.kubera.ui.oper.kewajiban.AddPajak a=new 
        raden.janoko.kubera.ui.oper.kewajiban.AddPajak(this, true, d);
            a.setVisible(true);
            while(a.isVisible()){}
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        }setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    }

    private void muatSemua() {
        //
    }

@SuppressWarnings("SleepWhileInLoop")
    private void lanjut() {
        new Thread(()->{
            while(this.isVisible())try {
                muatSemua();
                Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    raden.janoko.kubera.util.Work.hindar(ex);
                }
        }).start();setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }
}
